accounts:
  - name: alice
    coins: ["200000000stake"]
  - name: bob
    coins: ["100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["100000stake"]
