// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ride/next_ride.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type NextRide struct {
	IdValue uint64 `protobuf:"varint,1,opt,name=idValue,proto3" json:"idValue,omitempty"`
	// For simplicity, all this activity is consolidated into a single FIFO structure with a global deadline.
	FifoHead string `protobuf:"bytes,2,opt,name=fifoHead,proto3" json:"fifoHead,omitempty"`
	FifoTail string `protobuf:"bytes,3,opt,name=fifoTail,proto3" json:"fifoTail,omitempty"`
}

func (m *NextRide) Reset()         { *m = NextRide{} }
func (m *NextRide) String() string { return proto.CompactTextString(m) }
func (*NextRide) ProtoMessage()    {}
func (*NextRide) Descriptor() ([]byte, []int) {
	return fileDescriptor_81841ce7d665589f, []int{0}
}
func (m *NextRide) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NextRide) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NextRide.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NextRide) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NextRide.Merge(m, src)
}
func (m *NextRide) XXX_Size() int {
	return m.Size()
}
func (m *NextRide) XXX_DiscardUnknown() {
	xxx_messageInfo_NextRide.DiscardUnknown(m)
}

var xxx_messageInfo_NextRide proto.InternalMessageInfo

func (m *NextRide) GetIdValue() uint64 {
	if m != nil {
		return m.IdValue
	}
	return 0
}

func (m *NextRide) GetFifoHead() string {
	if m != nil {
		return m.FifoHead
	}
	return ""
}

func (m *NextRide) GetFifoTail() string {
	if m != nil {
		return m.FifoTail
	}
	return ""
}

func init() {
	proto.RegisterType((*NextRide)(nil), "smarshallspitzbart.ride.ride.NextRide")
}

func init() { proto.RegisterFile("ride/next_ride.proto", fileDescriptor_81841ce7d665589f) }

var fileDescriptor_81841ce7d665589f = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0xca, 0x4c, 0x49,
	0xd5, 0xcf, 0x4b, 0xad, 0x28, 0x89, 0x07, 0xb1, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x64,
	0x8a, 0x73, 0x13, 0x8b, 0x8a, 0x33, 0x12, 0x73, 0x72, 0x8a, 0x0b, 0x32, 0x4b, 0xaa, 0x92, 0x12,
	0x8b, 0x4a, 0xf4, 0xc0, 0xd2, 0x20, 0x42, 0x29, 0x86, 0x8b, 0xc3, 0x2f, 0xb5, 0xa2, 0x24, 0x28,
	0x33, 0x25, 0x55, 0x48, 0x82, 0x8b, 0x3d, 0x33, 0x25, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82, 0x51,
	0x81, 0x51, 0x83, 0x25, 0x08, 0xc6, 0x15, 0x92, 0xe2, 0xe2, 0x48, 0xcb, 0x4c, 0xcb, 0xf7, 0x48,
	0x4d, 0x4c, 0x91, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0xf3, 0x61, 0x72, 0x21, 0x89, 0x99,
	0x39, 0x12, 0xcc, 0x08, 0x39, 0x10, 0xdf, 0xc9, 0xeb, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4,
	0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f,
	0xe5, 0x18, 0xa2, 0x0c, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0xe1,
	0x0e, 0xd4, 0x85, 0xbb, 0x50, 0x1f, 0xec, 0x95, 0x0a, 0x08, 0x55, 0x52, 0x59, 0x90, 0x5a, 0x9c,
	0xc4, 0x06, 0xf6, 0x8e, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xdc, 0x5e, 0xa7, 0xe6, 0x00,
	0x00, 0x00,
}

func (m *NextRide) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NextRide) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NextRide) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FifoTail) > 0 {
		i -= len(m.FifoTail)
		copy(dAtA[i:], m.FifoTail)
		i = encodeVarintNextRide(dAtA, i, uint64(len(m.FifoTail)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FifoHead) > 0 {
		i -= len(m.FifoHead)
		copy(dAtA[i:], m.FifoHead)
		i = encodeVarintNextRide(dAtA, i, uint64(len(m.FifoHead)))
		i--
		dAtA[i] = 0x12
	}
	if m.IdValue != 0 {
		i = encodeVarintNextRide(dAtA, i, uint64(m.IdValue))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintNextRide(dAtA []byte, offset int, v uint64) int {
	offset -= sovNextRide(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NextRide) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IdValue != 0 {
		n += 1 + sovNextRide(uint64(m.IdValue))
	}
	l = len(m.FifoHead)
	if l > 0 {
		n += 1 + l + sovNextRide(uint64(l))
	}
	l = len(m.FifoTail)
	if l > 0 {
		n += 1 + l + sovNextRide(uint64(l))
	}
	return n
}

func sovNextRide(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozNextRide(x uint64) (n int) {
	return sovNextRide(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *NextRide) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowNextRide
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NextRide: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NextRide: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdValue", wireType)
			}
			m.IdValue = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNextRide
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IdValue |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FifoHead", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNextRide
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNextRide
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNextRide
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FifoHead = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FifoTail", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowNextRide
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthNextRide
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthNextRide
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FifoTail = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipNextRide(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthNextRide
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipNextRide(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowNextRide
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNextRide
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowNextRide
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthNextRide
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupNextRide
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthNextRide
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthNextRide        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowNextRide          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupNextRide = fmt.Errorf("proto: unexpected end of group")
)
