// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ride/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgRequestRide struct {
	Creator       string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	StartLocation string `protobuf:"bytes,2,opt,name=startLocation,proto3" json:"startLocation,omitempty"`
	Destination   string `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	MutualStake   uint64 `protobuf:"varint,4,opt,name=mutualStake,proto3" json:"mutualStake,omitempty"`
	HourlyPay     uint64 `protobuf:"varint,5,opt,name=hourlyPay,proto3" json:"hourlyPay,omitempty"`
	DistanceTip   uint64 `protobuf:"varint,6,opt,name=distanceTip,proto3" json:"distanceTip,omitempty"`
}

func (m *MsgRequestRide) Reset()         { *m = MsgRequestRide{} }
func (m *MsgRequestRide) String() string { return proto.CompactTextString(m) }
func (*MsgRequestRide) ProtoMessage()    {}
func (*MsgRequestRide) Descriptor() ([]byte, []int) {
	return fileDescriptor_c76036c41b1e8957, []int{0}
}
func (m *MsgRequestRide) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestRide) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestRide.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestRide) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestRide.Merge(m, src)
}
func (m *MsgRequestRide) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestRide) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestRide.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestRide proto.InternalMessageInfo

func (m *MsgRequestRide) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgRequestRide) GetStartLocation() string {
	if m != nil {
		return m.StartLocation
	}
	return ""
}

func (m *MsgRequestRide) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

func (m *MsgRequestRide) GetMutualStake() uint64 {
	if m != nil {
		return m.MutualStake
	}
	return 0
}

func (m *MsgRequestRide) GetHourlyPay() uint64 {
	if m != nil {
		return m.HourlyPay
	}
	return 0
}

func (m *MsgRequestRide) GetDistanceTip() uint64 {
	if m != nil {
		return m.DistanceTip
	}
	return 0
}

type MsgRequestRideResponse struct {
	IdValue string `protobuf:"bytes,1,opt,name=idValue,proto3" json:"idValue,omitempty"`
}

func (m *MsgRequestRideResponse) Reset()         { *m = MsgRequestRideResponse{} }
func (m *MsgRequestRideResponse) String() string { return proto.CompactTextString(m) }
func (*MsgRequestRideResponse) ProtoMessage()    {}
func (*MsgRequestRideResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c76036c41b1e8957, []int{1}
}
func (m *MsgRequestRideResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgRequestRideResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgRequestRideResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgRequestRideResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgRequestRideResponse.Merge(m, src)
}
func (m *MsgRequestRideResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgRequestRideResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgRequestRideResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgRequestRideResponse proto.InternalMessageInfo

func (m *MsgRequestRideResponse) GetIdValue() string {
	if m != nil {
		return m.IdValue
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgRequestRide)(nil), "smarshallspitzbart.ride.ride.MsgRequestRide")
	proto.RegisterType((*MsgRequestRideResponse)(nil), "smarshallspitzbart.ride.ride.MsgRequestRideResponse")
}

func init() { proto.RegisterFile("ride/tx.proto", fileDescriptor_c76036c41b1e8957) }

var fileDescriptor_c76036c41b1e8957 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xc1, 0x4e, 0x02, 0x31,
	0x10, 0x86, 0xa9, 0x20, 0x86, 0x12, 0x3c, 0xf4, 0x60, 0x1a, 0x43, 0x1a, 0x42, 0x3c, 0x70, 0xd0,
	0xc5, 0xa0, 0x4f, 0xe0, 0xd1, 0x48, 0x62, 0x56, 0xe3, 0xc1, 0x5b, 0xd9, 0x6d, 0xa0, 0x71, 0xd9,
	0x2e, 0x9d, 0x69, 0x02, 0x3e, 0x85, 0x8f, 0xe5, 0x91, 0x83, 0x07, 0x8f, 0x06, 0x5e, 0xc4, 0xd0,
	0x75, 0x71, 0xf7, 0x62, 0xe2, 0xa5, 0xcd, 0xfc, 0xf3, 0x75, 0xa6, 0xff, 0x0c, 0xed, 0x58, 0x1d,
	0xab, 0x21, 0x2e, 0x83, 0xcc, 0x1a, 0x34, 0xac, 0x0b, 0x73, 0x69, 0x61, 0x26, 0x93, 0x04, 0x32,
	0x8d, 0xaf, 0x13, 0x69, 0x31, 0xd8, 0x11, 0xfe, 0xe8, 0x7f, 0x10, 0x7a, 0x3c, 0x86, 0x69, 0xa8,
	0x16, 0x4e, 0x01, 0x86, 0x3a, 0x56, 0x8c, 0xd3, 0xa3, 0xc8, 0x2a, 0x89, 0xc6, 0x72, 0xd2, 0x23,
	0x83, 0x56, 0x58, 0x84, 0xec, 0x8c, 0x76, 0x00, 0xa5, 0xc5, 0x3b, 0x13, 0x49, 0xd4, 0x26, 0xe5,
	0x07, 0x3e, 0x5f, 0x15, 0x59, 0x8f, 0xb6, 0x63, 0x05, 0xa8, 0xd3, 0x9c, 0xa9, 0x7b, 0xa6, 0x2c,
	0xed, 0x88, 0xb9, 0x43, 0x27, 0x93, 0x07, 0x94, 0x2f, 0x8a, 0x37, 0x7a, 0x64, 0xd0, 0x08, 0xcb,
	0x12, 0xeb, 0xd2, 0xd6, 0xcc, 0x38, 0x9b, 0xac, 0xee, 0xe5, 0x8a, 0x1f, 0xfa, 0xfc, 0xaf, 0xe0,
	0x3b, 0x68, 0x40, 0x99, 0x46, 0xea, 0x51, 0x67, 0xbc, 0x99, 0xbf, 0x2f, 0x49, 0xfd, 0x11, 0x3d,
	0xa9, 0xba, 0x0a, 0x15, 0x64, 0x26, 0x05, 0xef, 0x4e, 0xc7, 0x4f, 0x32, 0x71, 0xaa, 0x70, 0xf7,
	0x13, 0x8e, 0x96, 0xb4, 0x3e, 0x86, 0x29, 0x5b, 0xd0, 0x76, 0x79, 0x1a, 0xe7, 0xc1, 0x5f, 0xf3,
	0x0b, 0xaa, 0x5d, 0x4e, 0xaf, 0xff, 0x43, 0x17, 0x7f, 0xba, 0xb9, 0x7d, 0xdf, 0x08, 0xb2, 0xde,
	0x08, 0xf2, 0xb5, 0x11, 0xe4, 0x6d, 0x2b, 0x6a, 0xeb, 0xad, 0xa8, 0x7d, 0x6e, 0x45, 0xed, 0xf9,
	0x72, 0xaa, 0x71, 0xe6, 0x26, 0x41, 0x64, 0xe6, 0xc3, 0x7d, 0xe5, 0x8b, 0x7d, 0xe9, 0xa1, 0x5f,
	0xf5, 0x32, 0xbf, 0x70, 0x95, 0x29, 0x98, 0x34, 0xfd, 0xd6, 0xaf, 0xbe, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x89, 0xbc, 0x6a, 0xb2, 0x06, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	RequestRide(ctx context.Context, in *MsgRequestRide, opts ...grpc.CallOption) (*MsgRequestRideResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) RequestRide(ctx context.Context, in *MsgRequestRide, opts ...grpc.CallOption) (*MsgRequestRideResponse, error) {
	out := new(MsgRequestRideResponse)
	err := c.cc.Invoke(ctx, "/smarshallspitzbart.ride.ride.Msg/RequestRide", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	RequestRide(context.Context, *MsgRequestRide) (*MsgRequestRideResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) RequestRide(ctx context.Context, req *MsgRequestRide) (*MsgRequestRideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestRide not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_RequestRide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgRequestRide)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RequestRide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/smarshallspitzbart.ride.ride.Msg/RequestRide",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RequestRide(ctx, req.(*MsgRequestRide))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "smarshallspitzbart.ride.ride.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestRide",
			Handler:    _Msg_RequestRide_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ride/tx.proto",
}

func (m *MsgRequestRide) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestRide) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestRide) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DistanceTip != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.DistanceTip))
		i--
		dAtA[i] = 0x30
	}
	if m.HourlyPay != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.HourlyPay))
		i--
		dAtA[i] = 0x28
	}
	if m.MutualStake != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.MutualStake))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Destination) > 0 {
		i -= len(m.Destination)
		copy(dAtA[i:], m.Destination)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Destination)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.StartLocation) > 0 {
		i -= len(m.StartLocation)
		copy(dAtA[i:], m.StartLocation)
		i = encodeVarintTx(dAtA, i, uint64(len(m.StartLocation)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgRequestRideResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgRequestRideResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgRequestRideResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.IdValue) > 0 {
		i -= len(m.IdValue)
		copy(dAtA[i:], m.IdValue)
		i = encodeVarintTx(dAtA, i, uint64(len(m.IdValue)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgRequestRide) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.StartLocation)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Destination)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.MutualStake != 0 {
		n += 1 + sovTx(uint64(m.MutualStake))
	}
	if m.HourlyPay != 0 {
		n += 1 + sovTx(uint64(m.HourlyPay))
	}
	if m.DistanceTip != 0 {
		n += 1 + sovTx(uint64(m.DistanceTip))
	}
	return n
}

func (m *MsgRequestRideResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.IdValue)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgRequestRide) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestRide: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestRide: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartLocation", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StartLocation = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Destination", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Destination = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MutualStake", wireType)
			}
			m.MutualStake = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MutualStake |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HourlyPay", wireType)
			}
			m.HourlyPay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HourlyPay |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistanceTip", wireType)
			}
			m.DistanceTip = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DistanceTip |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgRequestRideResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgRequestRideResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgRequestRideResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IdValue", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IdValue = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
